version: "3.8"

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "8000:8000"
    environment:
      - COHERE_API_KEY=${COHERE_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GPT_API_KEY=${GPT_API_KEY}
      - QWEN_API_KEY=${QWEN_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - ROGUEROSE_API_KEY=${ROGUEROSE_API_KEY}
      - META_API_KEY=${META_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./Backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./echo-ai-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    # Uncomment the next line for live reload in dev mode
    # volumes:
    #   - ./echo-ai-frontend:/app
    # This will serve the React static build from Nginx
